# Generated by Django 3.0.3 on 2020-12-09 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
