# Generated by Django 3.0.3 on 2020-12-13 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_auto_20201209_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='price',
        ),
    ]
