# Generated by Django 3.0.3 on 2020-12-15 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_auto_20201214_2214'),
        ('sales', '0005_remove_sale_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='items.Item'),
        ),
    ]
