# Generated by Django 3.0.3 on 2020-12-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_auto_20201215_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='profit',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
