# Generated by Django 3.0.3 on 2021-03-02 06:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_auto_20201215_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
