# Generated by Django 3.0.3 on 2021-03-02 06:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_auto_20210302_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
